FROM registry.scontain.com:5050/lequocdo/securetf:scone5.2.1-tensorflow2.4.1

ENV SCONE_MODE=hw

ADD image_files /

RUN pip install pillow

RUN mkdir /encrypted-output

CMD ["/usr/bin/python"]
